import { Currency } from '@wallettree/api-client'

export const CONTRACT_ADDRESSES = {
  [Currency.USDT.toString()]: '0xdac17f958d2ee523a2206206994597c13d831ec7',
}

export const CONTRACT_DECIMALS = {
  [Currency.USDT.toString()]: 6,
  [Currency.USDT_TRON.toString()]: 6,
  [Currency.INRT_TRON.toString()]: 2,
  [Currency.USDT_MATIC.toString()]: 6,
  [Currency.WBTC.toString()]: 8,
  [Currency.LEO.toString()]: 18,
  [Currency.LATOKEN.toString()]: 18,
  [Currency.COIIN.toString()]: 18,
  [Currency.RMD.toString()]: 18,
  [Currency.MATIC_ETH.toString()]: 18,
  [Currency.GMC.toString()]: 18,
  [Currency.GMC_BSC.toString()]: 18,
  [Currency.BUSD.toString()]: 18,
  [Currency.CAKE.toString()]: 18,
  [Currency.BUSD_BSC.toString()]: 18,
  [Currency.LINK.toString()]: 18,
  [Currency.UNI.toString()]: 18,
  [Currency.FREE.toString()]: 18,
  [Currency.MKR.toString()]: 18,
  [Currency.USDC.toString()]: 6,
  [Currency.HAG.toString()]: 8,
  [Currency.BAT.toString()]: 18,
  [Currency.TUSD.toString()]: 18,
  [Currency.PAX.toString()]: 18,
  [Currency.PAXG.toString()]: 18,
  [Currency.PLTC.toString()]: 18,
  [Currency.MMY.toString()]: 18,
  [Currency.XCON.toString()]: 18,
  [Currency.REVV.toString()]: 18,
  [Currency.SAND.toString()]: 18,
  [Currency.USDC_MATIC.toString()]: 6,
  [Currency.USDC_BSC.toString()]: 18,
  [Currency.B2U_BSC.toString()]: 18,
  [Currency.BETH.toString()]: 18,
  [Currency.BBTC.toString()]: 18,
  [Currency.BADA.toString()]: 18,
  [Currency.WBNB.toString()]: 18,
  [Currency.BDOT.toString()]: 18,
  [Currency.BXRP.toString()]: 18,
  [Currency.BLTC.toString()]: 18,
  [Currency.BBCH.toString()]: 18,
}
